### ISSUE TITLE
Humanoid前提でないVRMのサポート

### ISSUE THREAD

**Issue by kazu0617** [kazu0617/vrmtoglb_autoconvert#22]
主にボーン周りの挙動をオプション化すればよさそう。もっとも特殊例な気もするので別batにするのもありかも。

**Comment by kazu0617** [comment]
当面はHumanoidではないので他のツールでサポートしてもらうかも。リンク付けておいた方が親切？

**Comment by kazu0617** [comment]
Humanoid前提でないVRMの場合はそもそもリネームでOKな気がするのでいったん対応を除外したい。
@lill-la これってvrmconv.py側で判断してスキップとかできますかね。

**Comment by lill-la** [comment]
判定はわからないけど、ボーンの処理が異常系になっても無視して次の処理に行けるようにするだけでよさそう
たぶん #21 以外にも問題ありそうなので要調査

**Comment by lill-la** [comment]
単に例外握りつぶすだけでいいきがしてきた
モードの変更だけは直さないとだけど

**Comment by kazu0617** [comment]
一旦これで様子見てみる。
